spring:
  application.name: auth-service
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: ${DB_USER:TICTAC_APP}
    password: ${DB_PASS:tictacpass}
    driver-class-name: oracle.jdbc.OracleDriver
server.port: 8081
management.endpoints.web.exposure.include: "health,info"
app:
  jwt:
    issuer: tictac-auth
    secret: "dbfjasbfjbsfjsbdgkjsjkbsdklfjghsifgjhsvblkjxcvbsifxkjgcbvsifhkxcgbvsdifoxkhlcvbsdf oikxlcjbvsidofkljxcgbvlsifdkjvxcb ihsdflkxvblshdfkxbviksjfxvbl hfbxcvkjhb"
    ttl-seconds: 3600