# user-profile-service/src/main/resources/application.yml
spring:
  application:
    name: user-profile-service
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "health,info"